version: '3'

services:
  app:
    image: sanggenie/planus
    container_name: planus
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - redis

  redis:
    image: redis
    container_name: redis
    hostname: redis
    ports:
      - 6379:6379